version: "3"
services:
  fashionscape-api:
    container_name: fashionscape-api
    environment:
      - RS_HOST=api.rune.scape.fashion
    image: ncpierson/fashionscape-api:1.1.0
    restart: always
  # foundry-flora:
  #   container_name: foundry-flora
  #   env_file: foundry-flora/foundry.env
  #   image: felddy/foundryvtt:release
  #   restart: "unless-stopped"
  #   volumes:
  #     - /opt/foundry-flora:/data
  # foundry-ian:
  #   container_name: foundry-ian
  #   env_file: foundry-ian/foundry.env
  #   image: felddy/foundryvtt:release
  #   restart: "unless-stopped"
  #   volumes:
  #     - /opt/foundry-ian:/data
  proxy:
    container_name: proxy
    image: caddy:2.4.6
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /opt/caddy/data:/data
      - /opt/caddy/Caddyfile:/etc/caddy/Caddyfile
