version: "3"
services:
  foundry:
    container_name: foundry
    env_file: foundry.env
    image: felddy/foundryvtt:release
    restart: "unless-stopped"
    volumes:
      - /root/foundry-data:/data
  proxy:
    container_name: proxy
    image: caddy:2.4.6
    ports:
      - 80:80
      - 443:443
    restart: always
    volumes:
      - /root/foundry/Caddyfile:/etc/caddy/Caddyfile
  truthordrink:
    container_name: truthordrink
    image: floramoon/truthordrink-web:0.6.2
    restart: "unless-stopped"
  sheetfacts:
    container_name: sheetfacts
    image: floramoon/sheet-facts-web:0.6.2
    restart: "unless-stopped"
