version: "3"
services:
  blog:
    container_name: blog
    environment:
      - url=https://blog.nick.exposed
    image: ghost:2.31.1
    labels:
      - "traefik.http.routers.blog.rule=Host(`blog.nick.exposed`)"
      - "traefik.http.routers.blog.entrypoints=websecure"
      - "traefik.http.routers.blog.tls.certresolver=default"
    restart: always
    volumes:
      - /opt/ghost/content:/var/lib/ghost/content
  dashboard:
    container_name: dashboard
    image: ncpierson/nick.exposed:1.1.0
    labels:
      - "traefik.http.routers.dash.rule=Host(`nick.exposed`)"
      - "traefik.http.routers.dash.entrypoints=websecure"
      - "traefik.http.routers.dash.tls.certresolver=default"
    restart: always
  fashionscape-api:
    container_name: fashionscape-api
    image: ncpierson/fashionscape-api:0.3.2
    labels:
      - "traefik.http.routers.fashionscape-api.rule=Host(`api.scape.fashion`)"
      - "traefik.http.routers.fashionscape-api.entrypoints=websecure"
      - "traefik.http.routers.fashionscape-api.tls.certresolver=default"
      - "traefik.http.services.fashionscape-api.loadbalancer.server.port=8000"
    restart: always
  fashionscape-web:
    container_name: fashionscape-web
    image: ncpierson/fashionscape-web:0.3.3
    labels:
      - "traefik.http.routers.fashionscape-web.rule=Host(`scape.fashion`)"
      - "traefik.http.routers.fashionscape-web.entrypoints=websecure"
      - "traefik.http.routers.fashionscape-web.tls.certresolver=default"
    restart: always
  proxy:
    command:
      - "--api.insecure=true"
      - "--certificatesresolvers.default.acme.httpchallenge=true"
      - "--certificatesresolvers.default.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.default.acme.email=me@nick.exposed"
      - "--certificatesresolvers.default.acme.storage=acme.json"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--log.level=INFO"
      - "--providers.docker=true"
    container_name: proxy
    image: traefik:v2.0
    labels:
      - "traefik.http.routers.http-catchall.rule=hostregexp(`{host:.+}`)"
      - "traefik.http.routers.http-catchall.entrypoints=web"
      - "traefik.http.routers.http-catchall.middlewares=redirect-to-https"
      - "traefik.http.middlewares.redirect-to-https.redirectscheme.scheme=https"
    ports:
      - 80:80
      - 443:443
      - 8080:8080
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /opt/traefik/acme.json:/acme.json
  resume:
    container_name: resume
    image: ncpierson/resume:1.0.0
    labels:
      - "traefik.http.routers.resume.rule=Host(`resume.nick.exposed`)"
      - "traefik.http.routers.resume.entrypoints=websecure"
      - "traefik.http.routers.resume.tls.certresolver=default"
    restart: always
  soundoftext-api:
    container_name: soundoftext-api
    depends_on:
      - soundoftext-db
    env_file: soundoftext/soundoftext-api.env
    image: ncpierson/soundoftext-api:1.0.6
    labels:
      - "traefik.http.routers.soundoftext-api.rule=Host(`api.soundoftext.com`)"
      - "traefik.http.routers.soundoftext-api.entrypoints=websecure"
      - "traefik.http.routers.soundoftext-api.tls.certresolver=default"
      - "traefik.http.services.soundoftext-api.loadbalancer.server.port=5757"
    restart: always
  soundoftext-db:
    container_name: soundoftext-db
    image: mongo:4.2.0
    labels:
      - "traefik.enable=false"
    restart: always
    volumes:
      - /opt/soundoftext/db:/data/db
  soundoftext-web:
    container_name: soundoftext-web
    image: ncpierson/soundoftext-web:1.1.16
    labels:
      - "traefik.http.routers.soundoftext-web.rule=Host(`soundoftext.com`)"
      - "traefik.http.routers.soundoftext-web.entrypoints=websecure"
      - "traefik.http.routers.soundoftext-web.tls.certresolver=default"
    restart: always
